### ISSUE TITLE
Is @react-rxjs/core@0.6.0-1 a significant breaking change from 0.5.0?

### ISSUE THREAD

**Issue by ilikejames** [re-rxjs/react-rxjs#153]
Upgrading to `@react-rxjs/core@0.6.0-1` I can't get the most basic PoC to work. 

```ts
import React from "react";
import { bind, shareLatest } from "@react-rxjs/core";
import { timer } from "rxjs";
import { startWith } from 'rxjs/operators';

const [useTimer] = bind(() => timer(0, 1000).pipe(startWith(0), shareLatest()));

export default function App() {
  const timer = useTimer();
  return <div className="App">{timer}</div>;
}
```

```txt
Error
Missing subscription
```

[Code](https://codesandbox.io/s/react-rxjs060-xun7h?file=/src/App.js)

If this is due to breaking changes, a suggestion would be to expand [this exception message](https://github.com/re-rxjs/react-rxjs/blob/main/packages/core/src/internal/share-latest.ts#L93) to give more detail. Plus, to add a demo package with a few working examples to provide end users with  a sanity check.

If it is a regression, perhaps there can be some integration tests added.

**Comment by josepot** [comment]
Hi @ilikejames,

Yep, there was an important breaking change on `0.6` and we haven't had time to update the docs, yet. I'm very sorry about that. However, the breaking change [was documented in the release-notes of 0.6.0](https://github.com/re-rxjs/react-rxjs/releases/tag/%40react-rxjs%2Fcore%400.6.0). I like the suggestion of improving the exception message. I will leave this issue open until we've addressed that.

We also have to update the docs to show different ways of handling subscriptions. However, in the meanwhile, please have a look at the way that we are handling the subscriptions in the [re-architected version of ReactiveTrader](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/tree/master/src/new-client). More concretely, I think that these 2 examples can be pretty helpful: the [analytics component](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/Analytics/Analytics.tsx), and the [live-rates component](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/LiveRates/LiveRates.tsx).

Also, something worth pointing out is that since `v0.6.0`, `bind` accepts a second argument for "the default-value" if this argument is provided, that hook will never trigger `Suspense`. The reason being that the hook will return the provided default-value whenever the stream hasn't emitted or if the stream emits `SUSPENSE`, one thing to notice about this, though, is that the initial-subscription will happen after the component gets mounted, not on render.

**Comment by ilikejames** [comment]
Thanks for the comments, but I’m afraid I’m not following. 

Both examples you gave use the `<Subscribe/>` component. Whereas, [LineChart.tsx](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/Analytics/ProfitAndLoss/LineChart/LineChart.tsx#L75) appears to bind a stream directly, with no magic I can see following the upstream. 

 From my understanding of:
 
 > Breaking change: We are no longer making the initial subscription on render. It's now the responsibility of the user to make sure that the initial subscription is there before the hook consumes the **observable.
 
 That this could be achieved by: 
 
```ts
const [useTimer, timer$] = bind(() => timer(0, 1000).pipe(startWith(0), shareLatest()));

export default function App() {
  useSubscribe(timer$);
  const timer = useTimer();
  return <div>{timer}</div>;
}
```

```txt
 Missing Subscription
```

Or...

```ts
const _timer$ = timer(0, 1000)
_timer$.subscribe()
const [useTimer, timer$] = bind(() => _timer$.pipe(startWith(0), shareLatest()));

export default function App() {
  const timer = useTimer();
  return <div>{timer}</div>;
}
```
```text
 Missing Subscription
```

... or both *should* work, but don't.

We are using a *lot* of pre-0.6.0 code so I really like not to have to wrap everything with this component...
Is there a similar 5-ish line example that you can point me to? I feel like I've had to parse a whole lot of ReactiveTrader and still no wiser.

**Comment by josepot** [comment]
> Thanks for the comments, but I’m afraid I’m not following.

Sorry, I guess that I should have provided an explanation with more details.

> Both examples you gave use the <Subscribe/> component.

Yes, but notice what's been passed into the `source$` of `Subscribe`: a stream that's the result of merging the streams of the components that are in its children.

>  Whereas, LineChart.tsx appears to bind a stream directly, with no magic I can see following all the upstream.

That's not accurate, the LineChart component can only be used if the subscription to the `linechart$` stream that it exposes happens before the component gets rendered. Please, notice how the same file not only exports the `LineChart` component, it also exports a[ `lineChart$` stream](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/Analytics/ProfitAndLoss/LineChart/LineChart.tsx#L165), which is the "subscription" stream that this component needs in order to work. It's the responsibility of its consumer to ensure that the subscription happens before render, which can be accomplished in many different ways.

If we have a look at its consumer: the [`ProfitsAndLoss` component](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/Analytics/ProfitAndLoss/ProfitAndLoss.tsx), then we can see how that component is using 2 different components that need streams to work: `LastPosition` and `LineChart`.

Now, this component could use `Subscribe` and not propagate a stream to its parent. However, that's not the behavior that we want: we want to "suspend" the whole analytics section  while one of its 3 main components is still loading its data, therefore `ProfitAndLoss` also exports a `profitAndLoss$` stream that its consumer will have to subscribe before rendering the `ProfitAndLoss` component, and so on so forth... until there is a moment that we want to create a Suspense boundary, in that moment we use[ `Subscribe` (which is a super-set of `Suspense`) and that ensures that the subscription to that stream will take place before the children components are rendered](https://github.com/AdaptiveConsulting/ReactiveTraderCloud/blob/master/src/new-client/src/App/Analytics/Analytics.tsx#L14-L20). Think of `Subscribe` like a "provider".

We think that this pattern is very powerful, because thanks to it we can compose the "subscription" streams, in the same way that we compose components, and decide at which level we want to stop propagating the streams.

`useSubscribe` is pretty much useless since 0.6 and we are planning on removing it from the API.

> We are using a lot of pre-0.6.0 code so I really like not to have to wrap everything with this component...

You don't have to, you have options: you can use the pattern that I'm describing above, you can use the default-value of bind, you can use top-level subscriptions whenever needed, or a "router" that handles the subscriptions. We will try to document all these options as soon as we can. There have been other projects that had a lot of code in 0.5 and they have successfully migrated to 0.6. I admit that it can be a bit tedious,  and I sincerely apologize for that. However, the good news is that 0.5 is forward compatible with 0.6 and that can make the migration a bit less of a pain. That's why I will keep patching 0.5.

Once again, I'm very sorry that you had to go through this.

**Comment by ilikejames** [comment]
No need to apologise, though perhaps in future `0.6.0` could have been released as a prerelease version before the docs were updated ;)

I follow your last part and see that...

```ts
const [useTimer, timer$] = bind(
  timer(0, 1000).pipe(shareLatest())
, 0);
```

...works.

And after discussion with @voliva, using a default value in this way bypasses `Suspense` completely. So this is an option for the majority of our streams, and then we only need to use `<Subscribe/>` on the few stream that should trigger suspenseful behaviour in the ui. 

Ok. Thanks!

**Comment by voliva** [comment]
Hey @ilikejames - glad that you're finding a solution.

A quick note however, just to clarify:

```ts
const [useTimer, timer$] = bind(
  timer(0, 1000).pipe(shareLatest())
, 0);

const [useTimerSum, timerSum$] = bind(
  timer$.pipe(scan((a,b) => a+b))
);
```

In this example, `useTimer` can be used without needing a `<Subscribe />` boundary, but `useTimerSum` does, even if theoretically it wouldn't dispatch suspense (and will throw "Missing subscription" if used straight away).

This is because `bind` can't really know if a stream is doing something that would become asynchronous. To avoid this (without using `<Subscribe />`), useTimerSum also would need a defaultValue

**Comment by hoclun-rigsep** [comment]
Do I understand correctly then that <Subscribe> once again requires the `source$` prop?

**Comment by voliva** [comment]
> Do I understand correctly then that `<Subscribe>` once again requires the `source$` prop?

No, that hasn't change. From `core@0.8.0` (released late April) it became optional, and this hasn't changed since then.
