### ISSUE TITLE
Use native react use-sync-external-store instead of package

### ISSUE THREAD

**Issue by mbret** [re-rxjs/react-rxjs#295]
possibly reducing package size

**Comment by josepot** [comment]
As stated in the `peerDependencies` section of  its package.json, the [current version of `@react-rxjs/core` is intended to work with `react >=16.8.0`](https://github.com/re-rxjs/react-rxjs/blob/155fb04484099500cbf85806bf1fc0d4a6046c84/packages/core/package.json#L38-L41).

Does that mean that because of that users of React >18 will end up having an larger bundle size on their production built? 

Not at all. I'm using React 18 in a couple of projects myself and my production built doesn't include the code for the shim. The reason being that most bundlers are able to tree-shake [this code](https://github.com/facebook/react/blob/0131d0cff40d4054ac72c857d3a13c5173c46e0a/packages/use-sync-external-store/src/useSyncExternalStoreShim.js#L21). I mean, perhaps there are some bundlers which in some situations are not able to tree-shake that code. I would be a bit surprised about that, but I guess that's possible. Are you running into that issue? Does your production built include the code for the shim? If that's the case: could you please share a link of a project/repo that has that issue? :pray: 

It's possible that in the future we will end up dropping support for versions prior to React 18, in which case we will stop using the [official `use-sync-external-store` package](https://www.npmjs.com/package/use-sync-external-store) provided by the React core team. However, we don't see the need for that at the moment.

**Comment by mbret** [comment]
Clear answer, thank you

> Are you running into that issue?

I haven't checked
